### ISSUE TITLE
Missing Binary Sensors for Automation

### ISSUE THREAD

**Issue by Sn00kiT** [limengdu/MR24HPC1_HomeAssistant#5]
There is no usable sensors for reasonable automations.
Can you add 2 Sensors?

Like in this config:
https://github.com/thefipster/esphome-mmwave-sensors
https://github.com/thefipster/esphome-mmwave-sensors/blob/main/packages/mr24hpc1.yaml

![2023-05-27 21_17_15-GitHub - thefipster_esphome-mmwave-sensors_ ESPHome integration for mmWave Senso](https://github.com/limengdu/MR24HPC1_HomeAssistant/assets/77878228/e9e74b8c-e6bb-4288-a810-e7e26a0ad91d)

**Comment by limengdu** [comment]
This looks like great advice and I'll refer to them to refine my process!

**Comment by drothenberger** [comment]
I have to create my own sensor template to use the device in automations. It would be nice if these sensors were included by default.

**Comment by limengdu** [comment]
The latest project address of the kit will simplify all processes, please refer to the link here:
https://github.com/limengdu/mmwave-kit-external-components/tree/main
