### ISSUE TITLE
[Bug] Cannot change Motion To Rest Time Setting

### ISSUE THREAD

**Issue by tomaae** [limengdu/MR24HPC1_HomeAssistant#6]
Hello,
It is not possible to change "Motion To Rest Time Setting". It will stay at 3000ms no matter what. So getting presence is fast, but detecting that nobody is there has a long timeout that cannot be changed.
I went through available documentations and everything seems to be correct, but when it comes to hex codes, I'm far from knowledgeble at it.

**Comment by limengdu** [comment]
Hello, Motion To Rest Time Setting is the function to customize the mode setting. You need to be in custom mode to be allowed to set this value. You are not allowed to set this parameter in standard mode. For more detailed setting rules and explanation of the parameters, please refer to the user manual of the product: https://files.seeedstudio.com/wiki/mmWave-radar/MR24HPC1_User_Manual-V1.5.pdf
You can also read our Wiki content to understand the logic and usage of custom settings:
https://wiki.seeedstudio.com/mmwave_human_detection_kit/#custom-settings

**Comment by tomaae** [comment]
yup, that kinda works for most parts. but sensor is still not usable since once it detects presence, it wont ever go out of presence detected state.
But thats not an issue with this project most likely.
